project:
  type: website
  output-dir: docs

website:
  title: "Anny D. Rodriguez, Ph.D., MPH"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: experience.qmd
        text: Experience
      - href: projects.qmd
        text: Projects & Publications
      - href: skills.qmd
        text: Skills
      - href: contact.qmd
        text: Contact


format:
  html:
    theme:
      - flatly
      - custom.scss
    css: styles.css
    toc: true

editor: visual


